### ISSUE TITLE
Angular build with Warning: export 'ɵa24' was not found in '@angular/material/tabs'

### ISSUE THREAD

**Issue by gopumon** [angular/material2#11416]
I recently upgraded my project to Angular 6 and Angular Material 6 (v6.0.2 to be precise) following the instructions at [update.angular.io](https://update.angular.io/). After upgrade, on `ng serve` it compiles with some warnings as below.
```
WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵa24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵb24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵc24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵd24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵe24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵf24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵg24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵh24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵi24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵj24' was not found in '@angular/material/tabs'

WARNING in ./node_modules/@angular/material/esm5/material.es5.js
40:0-371 "export 'ɵk24' was not found in '@angular/material/tabs'
```
I am using only SnackBar and Dialog components. Any feedback on this are much appreciated.

**Comment by CaselIT** [comment]
I've the same problem. But it appears to be working even with the warning

**Comment by crh225** [comment]
I just upgraded angular and material to latest and it went away

**Comment by CaselIT** [comment]
I've updated to version 6.1.0 and I no longer have the warnings, so whatever it was it seems to be fixed

**Comment by gopumon** [comment]
Yes the warnings disappeared after updating to 6.1.0

**Comment by ashishkrjain** [comment]
I have updated material to v6.2.0 but still warnings shown on production build.any help?

**Comment by ashishkrjain** [comment]
Once all my project dependencies been updated to RxJS 6, I removed rxjs- compat and after that all warnings disappeared. Also on production build i was facing error "TypeError: t is not a function" that also gone after it.

**Comment by mxchange** [comment]
I'm on 6.2.1 and the warnings show

**Comment by ardatan** [comment]
Same warnings shown in the latest version of `@ngtools/webpack` and `@angular/material`.

**Comment by ardatan** [comment]
@gopumon  All dependencies including `rxjs` are up-to-date.

**Comment by gopumon** [comment]
@ardatan I am not getting the warnings with angular 6.0.4 and angular material 6.2.1. 

You may try the below : 

Remove deprecated RxJS 6 features using rxjs-tslint auto update rules.

For most applications this will mean running the following two commands:
```
yarn global add rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json
```


Once you and all of your dependencies have updated to RxJS 6, remove `rxjs-compat`.

**Comment by pfeigl** [comment]
I think you guys are actually affected by what is described here: #11664 
Long story short, delete node_modules and install again, should fix the problem.

**Comment by ardatan** [comment]
@pfeigl reinstalling node_modules worked for me, thank you!

**Comment by alexfung888** [comment]
doesn't work for me.
I found that reinstalling angular/material@=6.2.0 removes the problem.
If you install the latest 6.2.1, the package still calls itself 6.2.0, but  give the above list of warning when compiling.
Seems it doesn't matter whether you use cdk@620 or 621.

**Comment by alexfung888** [comment]
@pfeigl Yarn. Perhaps my installation of 621 was faulty. I'll try doing it again.

**Comment by alexfung888** [comment]
@pfeigl It is very repeatable on two machines on different internet connections. If I yarn add material@6.2.1 or @latest, the project will not serve, and the module has a package.json saying 6.2.0. If I yarn add material@=6.2.0 then it compiles without problem.

**Comment by alexfung888** [comment]
I think I solved my situation, although I don't know why.
If I install 621 normally, the module installed calls itself 620. However, as indicated above, the 621 in the registry correctly calls itself 621. More so, the 621 in my Yarn cache also calls itself 621. I have no idea where my bad 621 is installed from.
My resolution is to clear the yarn cache, remove the module and install it again. Seems this works (and any proper subset of these 3 actions does not -- you need to do all three).

**Comment by mariusc09** [comment]
same issue here too, reinstalling node_modules worked for me too, thank you @pfeigl!

**Comment by chaddoncooper** [comment]
+1 for the rm -rf of node-modules

**Comment by alexfung888** [comment]
yet the problem is coming back time after time. Every single time I upgrade @angular/material, on each of my machine using `yarn upgrade`, I ran into the same problem again. Then I need to `yarn remove` and `yarn add` material, after which the warnings disappeared.

**Comment by gopumon** [comment]
it looks like a problem with the `yarn` ecosystem.

**Comment by alexfung888** [comment]
@gopumon maybe, but it only happens with material, not even cdk.

**Comment by CardzMania** [comment]
rm -rf node-module ftw!

**Comment by alexfung888** [comment]
@CardzMania that is an overkill. As I said above, you only need to `yarn remove @angular/material` and add it back. No need to touch other modules.

However, you need to do this **every single time** you upgrades the material module.

**Comment by alexfung888** [comment]
Seems solved with latest devkit:
"@angular-devkit/build-angular": "0.7.0-rc.0",

**Comment by georgekarkuzashvili** [comment]
Thank you @alexfung888, you solved my problem!

**Comment by alexfung888** [comment]
but the problem return when I upgrade to material@6.3.3

**Comment by helenegodart** [comment]
Updating @angular-devkit/build-angular to 0.7.0-rc.2 worked for me today, don't know if this will be sustainable but that solved the issue at least for a time...

**Comment by johannesjo** [comment]
This reoccured for me when using yarn on 7.2.2 and 7.3.0.

**Comment by njdullea** [comment]
Occurred on Angular: 7.2.13 and Angular material: 8.0.0. Using NPM. Removing and reinstalling node_modules did not fix the issue.
