### PR TITLE
build(cdk): add bazel ng_module rules

### PR DESCRIPTION
**Pull request by jelbourn**
Part of #8369 

This is setup for eventually switching everything to bazel. It does not affect our real build yet.

cc @DevVersion

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -39,11 +40,14 @@
     "zone.js": "^0.8.12"
   },
   "devDependencies": {
+    "@angular/bazel": "^5.0.1",
     "@angular/compiler-cli": "^5.0.0",
     "@angular/http": "^5.0.0",
     "@angular/platform-browser-dynamic": "^5.0.0",
     "@angular/platform-server": "^5.0.0",
     "@angular/router": "^5.0.0",
+    "@angular/upgrade": "^5.0.1",
```
Comment (alexeagle) [inline package.json]: any particular reason you added upgrade?

File: src/cdk/a11y/BUILD.bazel [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+ng_module(
+  name = "a11y",
+  srcs = glob(["**/*.ts"], exclude=["**/*.spec.ts"]),
+  module_name = "@angular/cdk/a11y",
+  deps = [
+    "//src/cdk/coercion",
+    "//src/cdk/keycodes",
+    "//src/cdk/platform",
+  ],
+  tsconfig = ":tsconfig-build.json",
```
Comment (alexeagle) [inline src/cdk/a11y/BUILD.bazel]: note, you might want to try using the same tsconfig for all the rules, and have it be the one the editor uses too

File: BUILD.bazel [hunk 3]
```diff
@@ -0,0 +1,35 @@
+package(default_visibility = ["//visibility:public"])
```
[the remark this answers is not in the document]
Comment (jelbourn) [reply BUILD.bazel]: If I try to use that here I get:

```
ERROR: /usr/local/google/home/jelbourn/.cache/bazel/_bazel_jelbourn/2010aad45cf3f55bb7127948064a6254/external/build_bazel_rules_typescript/internal/tsc_wrapped/BUILD.bazel:19:1: Target '//:node_modules' is not visible from target '@build_bazel_rules_typescript//internal/tsc_wrapped:tsc_bin'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /usr/local/google/home/jelbourn/.cache/bazel/_bazel_jelbourn/2010aad45cf3f55bb7127948064a6254/external/build_bazel_rules_typescript/internal/tsc_wrapped/BUILD.bazel:19:1: Target '//:node_modules' is not visible from target '@build_bazel_rules_typescript//internal/tsc_wrapped:tsc_bin'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//src/cdk/observers:observers' failed; build aborted: Analysis of target '@build_bazel_rules_typescript//internal/tsc_wrapped:tsc_bin' failed; build aborted
INFO: Elapsed time: 0.833s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

For the rest of the rules I'm not too concerned about it right now

File: BUILD.bazel [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+# This rule belongs in node_modules/BUILD
+# It's here as a workaround for
+# https://github.com/bazelbuild/bazel/issues/374#issuecomment-296217940
+filegroup(
+  name = "node_modules",
+  # Performance workaround: list individual files
+  # Reduces the number of files as inputs to nodejs_binary:
+  # bazel query "deps(:node_modules)" | wc -l
+  # This won't scale in the general case.
+  # TODO(alexeagle): figure out what to do
```
[the remark this answers is not in the document]
Comment (jelbourn) [reply BUILD.bazel]: Doesn't strike me as that bad- you want to be explicit about your dependencies anyway

File: WORKSPACE [hunk 5]
```diff
@@ -0,0 +1,38 @@
+workspace(name = "angular_material_src")
+load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
```
[the remark this answers is not in the document]
Comment (jelbourn) [reply WORKSPACE]: Done, didn't know that was a thing.

File: angular.tsconfig.json [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+    "experimentalDecorators": true,
+    "types": []
+  },
+  "include": [
+    "node_modules/@angular/**/*"
+  ],
+  "exclude": [
+    "node_modules/@angular/bazel/**",
+    "node_modules/@angular/compiler-cli/**",
+    // Workaround bug introduced by 079d884
```
[the remark this answers is not in the document]
Comment (jelbourn) [reply angular.tsconfig.json]: Removed

File: package.json (hunk 1 above)
Comment (jelbourn) [reply package.json]: Without it the router fails the `postinstall` ngc:
```
> ngc -p angular.tsconfig.json

node_modules/@angular/router/upgrade/src/upgrade.d.ts(9,31): error TS2307: Cannot find module '@angular/upgrade/static'.
```

File: src/cdk/a11y/BUILD.bazel (hunk 2 above)
Comment (jelbourn) [reply src/cdk/a11y/BUILD.bazel]: Impossible presently because we need to specify a different `flatModuleId` for each package, but would be nice long term.

File: WORKSPACE [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+  tag = "0.0.2",
+)
+
+load("@io_bazel_rules_sass//sass:sass.bzl", "sass_repositories")
+sass_repositories()
+
+# Add TypeScript rules
+local_repository(
+  name = "build_bazel_rules_typescript",
+  path = "node_modules/@bazel/typescript",
```
Comment (DevVersion) [inline WORKSPACE]: We should explicitly specify this a dependency: https://www.npmjs.com/package/@bazel/typescript
