### ISSUE TITLE
createOverlayContainer is not a function after upgrading to 7.2

### ISSUE THREAD

**Issue by drager** [angular/material2#1050]
#### Bug

I just updated Angular material 2 to 7.2 from 6.0 and now the application wont start up. It throws the following error: `createOverlayContainer is not a function`. This is the following code I have when I'm bootstraping:

```typescript
import {bootstrap} from '@angular/platform-browser-dynamic'
import {HAMMER_GESTURE_CONFIG} from '@angular/platform-browser'
import {HTTP_PROVIDERS, Http} from '@angular/http'
import {provide} from '@angular/core'
import {Renderer} from '@angular/core'
import {APP_BASE_HREF} from '@angular/common'
import {disableDeprecatedForms, provideForms} from '@angular/forms'
import {OVERLAY_CONTAINER_TOKEN} from '@angular2-material/core/overlay/overlay'
import {createOverlayContainer} from '@angular2-material/core/overlay/overlay-container'
import {MdGestureConfig} from '@angular2-material/core/gestures/MdGestureConfig'
import {MdIconRegistry} from '@angular2-material/icon/icon-registry'

import {App} from './app/app'
import {APP_ROUTE_PROVIDER} from './app/routes'

bootstrap(App, [
  disableDeprecatedForms(),
  provideForms(),
  APP_ROUTE_PROVIDER,
  provide(OVERLAY_CONTAINER_TOKEN, {useValue: createOverlayContainer()}),
  HTTP_PROVIDERS,
  MdIconRegistry,
  Renderer,
  provide(HAMMER_GESTURE_CONFIG, {useClass: MdGestureConfig})
]).catch(err => console.error(err))
```

Could not find any breaking change about this in the changelog.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular version: 2.0.0-rc.4
Angular material version: 2.0.0-alpha.7-2

**Comment by jelbourn** [comment]
Ah, this was missed from the changelog. `OVERLAY_CONTAINER_TOKEN` is gone, there's a new `OverlayContainer` injectable. If you migrate to `NgModule`, however, you won't need to provide anything at all for Overlays.

**Comment by drager** [comment]
Alright, thanks!
