### ISSUE TITLE
MatAutoComplete- valueChanges.startWith is not a function

### ISSUE THREAD

**Issue by turab007** [angular/material2#8630]
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
This is my code which worked fine before updating material and angular
`filterUsers() {

    this.filteredData = this.searchForm.get('name').valueChanges
      .startWith(null)
      .map(val => this.filterResult(val));
  }`

#### What is the current behavior?
I get the following error 
`core.js:1350 ERROR TypeError: this.searchForm.get(...).valueChanges.startWith is not a function`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using the following versions 
  "@angular/animations": "^5.0.0-rc.0",
    "@angular/cdk": "^5.0.0-rc.1",
    "@angular/common": "^5.0.0-rc.0",
    "@angular/compiler": "^5.0.0-rc.0",
    "@angular/core": "^5.0.0-rc.0",
    "@angular/forms": "^5.0.0-rc.0",
    "@angular/http": "^5.0.0-rc.0",
    "@angular/material": "^5.0.0-rc.1",

 "typescript": "^2.5.3"

#### Is there anything else we should know?
It was working fine on angular 4.2.0 and material 2.0.0-beta-6. I recently updated them.

**Comment by donroyco** [comment]
As of[ beta.8](https://github.com/angular/material2/compare/2.0.0-beta.7...2.0.0-beta.8) you need to import RxJS operators explicitly:

> Angular Material no longer adds RxJS operators to the prototype of Observable. If your app depended on these operators being added by Angular Material, you will need to import them explicitly.

**Comment by turab007** [comment]
Thanks. this solved my issue.
