### PR TITLE
fix: material not working with ES2015

### LINKED ISSUE #13695: table: tsconfig target es6 causes `_elementRef` failure during table creation
#### Bug, feature request, or proposal:
Seems like all of my uses of `<mat-table>` and `<table mat-table>` broke with an undefined `elementRef` after upgrading from 6.1.x to 7.0.0 using `ng update`.

#### What is the expected behavior?

Tables should render and not throw an error on start.

#### What is the current behavior?

I receive the following error.

```
core.js:15043 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined
TypeError: Cannot read property 'nativeElement' of undefined
    at new CdkTable (table.js:1071)
    at new MatTable (table.js:28)
    at createClass (core.js:23001)
    at createDirectiveInstance (core.js:22828)
    at createViewNodes (core.js:24376)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at createViewNodes (core.js:24405)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at new CdkTable (table.js:1071)
    at new MatTable (table.js:28)
    at createClass (core.js:23001)
    at createDirectiveInstance (core.js:22828)
    at createViewNodes (core.js:24376)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at createViewNodes (core.js:24405)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16954)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```

`_elementRef` is undefined for some reason.
image

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Setup any type of mat-table and the cdk table constructor doesn't get it's element ref injected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0 w/ angular 7.0.0 on chrome 70.0.3538.67 (Official Build) (64-bit)

#### Is there anything else we should know?
Seems to be working on the docs. Wondering if it's just with upgraded apps? Going to check if a new gen app works with table.

### PR DESCRIPTION
**Pull request by DevVersion**
Fixes that Angular Material cannot be used with ES2015. See #12760 for detailed information. We already had a workaround applied, but this improves the workaround because it only partially worked for classes where no attributes were defined.

Fixes #13695.

### CODE REVIEW

File: src/lib/expansion/expansion-panel.ts [hunk 1]
```diff
@@ -40,9 +40,6 @@ import {matExpansionAnimations} from './expansion-animations';
 import {MatExpansionPanelContent} from './expansion-panel-content';
 import {MAT_ACCORDION, MatAccordionBase} from './accordion-base';
 
-// TODO(devversion): workaround for https://github.com/angular/material2/issues/12760
-export const _CdkAccordionItem = CdkAccordionItem;
```
Comment (mmalerba) [inline src/lib/expansion/expansion-panel.ts]: does this one need the `ctorParameters` forwarding?

Comment (DevVersion) [reply src/lib/expansion/expansion-panel.ts]: It no longer needs the workaround because there is an explicit constructor for the `MatExpansionPanel` class now.

**Comment by epelc** [comment]
@DevVersion are you sure this works? I'm getting the same error with material and cdk 7.0.1

**Comment by DevVersion** [comment]
@epelc Pretty confident. I've confirmed it locally when submitting the PR. Also this fix isn't part of v7.0.1. Can you please check with `master` and let me know? Thanks!

**Comment by epelc** [comment]
@DevVersion Is there a way to install master easily with npm?

**Comment by DevVersion** [comment]
@epelc Yeah you could do `npm i github:angular/{material2,cdk}-builds`

**Comment by epelc** [comment]
@DevVersion Thanks I'll try it out. I think your fix didn't make it into 7.0.1 looking at the git history now

**Comment by DevVersion** [comment]
@epelc Awesome. Thanks! and yeah, exactly. The fix is _not_ part of `7.0.1`.

**Comment by epelc** [comment]
@DevVersion Yeah my bad I realized cmd+f some old similar fix in the change log once 7.0.1 came out.

I'm not sure if this is just me but I got a different error about ctor parameters when testing with master.

image


Looks like it's trying to call `.map` on an anonymous function? 

NOTE this line works a bunch but at some point it gets passed an anonymous function which obvisouly doesn't have a map method since it's not an array(I just set a breakpoint for `!ctorParameters.map` to catch it). 
image

I looked into it a bit and I think it might be something to do with maybe these anon functions not being called or something? I don't have it setup to test and I know little about this ctor/compilation bugs inner workings so might be easier you to checkout?

```
(MatTable as any)['ctorParameters'] = () => (CdkTable as any)['ctorParameters'];
```

**Comment by DevVersion** [comment]
Thanks for checking that out. I'm not sure what's different in your scenario, but I can see why this "could" fail. I will push some safety changes to a PR tomorrow. Thanks again.

**Comment by DevVersion** [comment]
Also while you're at it, where is the code you shared in the second screenshot? Are those constants defined within a class?

**Comment by epelc** [comment]
It was if you click the `core.js:1394` link from the error(see first pic). I believe it is coming from the new `ctorParameters` properties you added in this current pr. That line only errors out when it gets to the new ones which are anonymous functions instead of arrays. I believe you might need to change to something like `ctorParameters = CdkTable['ctorParamters']` instead of having a function definition but I may be wrong.

Here is a larger screenshot that may help 
image


Also my testing repo with exactly what I'm using(standard cli project + basic table + target=es2015) https://github.com/epelc/bad-material-table

**Comment by DevVersion** [comment]
I see, these are the reflection capabilities from Angular core. This definitely helps. Thanks again.

Also regarding just assigning the `ctorParameters` without the function, we need a function with a different reference because otherwise Angular won't even read the `ctorParameters` from `MatTable`.

I will have a look tomorrow. Will keep you updated. At first glance, it just looks like the `CdkTable`  metadata is somehow not accessable.

**Comment by sishbi** [comment]
Is there a timeline for when this fix will get into a release?
Or is there someway I can use this fix from the master branch in my project?

**Comment by DenysVuika** [comment]
Trying to upgrade an application to 7.0.2, and got hundreds of unit tests now failing with `TypeError: ctorParameters.map is not a function`

**Comment by DenysVuika** [comment]
@DevVersion we are blocked by two releases already. Just upgraded to 7.0.3 and this damn thing (sorry) keeps failing with `ctorParameters.map is not a function`

**Comment by sishbi** [comment]
If you downgrade the target version in the tsconfig.json to es5 it works, which is what I did...
But I would still like to have a proper fix!

**Comment by DevVersion** [comment]
@DenysVuika Sorry, but unfortunately applying workarounds let to other problems which aren't really solvable in a way that still keeps the workaround in an acceptable way.

Since the whole issue is actually an **Angular bug** that will be fixed with https://github.com/angular/angular/commit/95743e3a64b61a6223b7755d6c9931dcb245979f (so future Angular `v7.1.0` release), I'm tending to delete the whole workaround.

cc. @jelbourn for thoughts.

**Comment by knoefel** [comment]
Still not working after upgrade to 7.1!

**Comment by DevVersion** [comment]
Yeah, there are still some issues with `@angular/core`. I've created https://github.com/angular/angular/issues/27267 to track this.

**Comment by CreepyGnome** [comment]
What is the status of Angular Material working with ES2015?  Issue https://github.com/angular/angular/issues/27267 shows it was fixed by https://github.com/angular/angular/pull/29232. That last one was closed fixed almost 2 months ago.

This has become a blocker as if you need to use a feature that requires es2015 (ie Map and iterate features of it) you cannot because enabling this breaks Angular Material.

**Comment by nhhockeyplayer** [comment]
I am unable to use mat-sidenav

```
ERROR TypeError: Cannot read property 'runOutsideAngular' of undefined
    at new MatDrawer (sidenav.js:203)
```

I switched my target
`        "target": "es2018",`

I thought it was safe to bump target to es2018 

```
Angular CLI: 7.3.9
Node: 8.12.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
```

**Comment by nhhockeyplayer** [comment]
actually I upgraded to latest angular and typescript and everything works

some good feedback

```
Angular CLI: 7.3.9
Node: 8.12.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.19
@angular/http                     7.2.15
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.29.0

```
