### ISSUE TITLE
Putting a type on an input+MdInputDirective throws an error when in a MdDialog

### ISSUE THREAD

**Issue by fredguile** [angular/material2#4590]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I'm using the standard html5 datetime picker for now, I've just upgraded to 2.0.0-beta.5. I wish I could update this to the new DatePicker but in the meantime I'll use:

```
<md-input-container>
   <input mdInput type="datetime-local" placeholder="Shipment date" formControlName="shipmentDate">
</md-input-container>
```

#### What is the current behavior?
It works fine within a normal template.

But from a MdDialog I'm getting an error since 2.0.0-beta.5:

```
ShipmentScheduleDialogComponent.html:6 ERROR TypeError: this._renderer.setProperty is not a function
    at MdInputDirective.set [as type] (material.es5.js:15106)
    at updateProp (core.es5.js:11059)
    at checkAndUpdateDirectiveInline (core.es5.js:10755)
    at checkAndUpdateNodeInline (core.es5.js:12216)
    at checkAndUpdateNode (core.es5.js:12155)
    at debugCheckAndUpdateNode (core.es5.js:12858)
    at debugCheckDirectivesFn (core.es5.js:12799)
    at Object.View_ShipmentScheduleDialogComponent_0.currVal_0 [as updateDirectives] (ShipmentScheduleDialogComponent.html:6)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12784)
    at checkAndUpdateView (core.es5.js:12122)
```

#### What are the steps to reproduce?

You can past the above template code, it will work in a standard template, but throws the above error within a Dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.2, Material 2.0.0-beta.5, macOS, Chrome, Typescript 2.3.2

#### Is there anything else we should know?
It worked on 2.0.0-beta.3

**Comment by willshowell** [comment]
Think you could repro in a plunker?

I tried, but not seeing the error https://plnkr.co/edit/9uwReM0dDLoHhoJOtnRL?p=preview

**Comment by crisbeto** [comment]
I wasn't able to reproduce it with any of the dialog setups. Can you post your config @fredguile?

**Comment by fredguile** [comment]
I didn't manage to reproduce so far in plunkr, but in the meantime I can provide a bit more details about what happens at runtime:

![screen shot 2017-05-26 at 19 13 42](https://cloud.githubusercontent.com/assets/209813/26505077/94117b80-4247-11e7-9e51-3c6baea25955.png)

What's gets injected into MdInputDirective::_rendering is an object that looks like:
{ delegate: DebugRenderer2 }

So it turns out that this._renderer.setStyle isn't defined, however naturally this._renderer.delegate.setStyle is.

I'm not quite familiar with this injected delegate mecanism, do you kow what it is? and if DI is happening correctly on my side? First time I'm having a DI issue btw...

**Comment by jelbourn** [comment]
@kara and I have seen this problem elsewhere. We found it usually happens when combining flex-layout directives and material directives on the same element, but haven't been able to track down the exact cause. We haven't been able to create a reduced test case for reproduction, but our best guess is that there's some bug in Angular itself that's injecting the wrong `Renderer` in certain circumstances.

**Comment by fredguile** [comment]
You're might be right, my templates are full of flex-layout. My workaround for now is to switch to the Material 2 `DatePicker` (whose DateAdapter reveals to be helpful for parsing/formatting datetimes), hence removing any "type" attributes on my `MdInputs`.

Hope that this can bring some knowledge to investigate further on Angular side.

**Comment by willshowell** [comment]
@fredguile The error only appears when you open your dialog right? Could you share more of your dialog content template?

**Comment by fredguile** [comment]
Yes sure (albeit the error doesn't kicks in Plunkr): http://plnkr.co/edit/2OODWRYZcoE5pJhKRtdk?p=preview

**Comment by crisbeto** [comment]
Closing since this issue is very old and is probably obsolete, because we don't use the renderer API anymore.
