### ISSUE TITLE
datepicker opens but is blank with build-optimizer (aot) enable

### ISSUE THREAD

**Issue by scotthardin** [angular/material2#12199]
#### Bug, feature request, or proposal:
mat-datepicker fails to open and throws error when compiled with: 
ng cli build --prod --build-optimizer 

This appears in @angular/cdk / @angular/material version 6.3.3.  It was working in version 6.2.1.

#### What is the expected behavior?
Same behavior as without build-optimizer

#### What is the current behavior?
Doesn't open on click and immediately throws error with build-optimizer option:

ERROR Error: Unable to process animations due to the following failed trigger transitions
 @transformPanel has failed due to:
- `query("@fadeInCalendar")` returned zero elements. (Use `query("@fadeInCalendar", { optional: true })` if you wish to allow this.

#### What are the steps to reproduce?
Compile ng cli project with angular material, add mat-datepicker, compile with: 
ng build --prod --build-optimizer

#### What is the use-case or motivation for changing an existing behavior?
Needs to work with aot

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 6.0.9
mat 6.3.3

**Comment by DevVersion** [comment]
I tried to setup a project that does exactly what you described, but I was not able to reproduce that. Can you provide a demo that shows the issue?

**Comment by tobang** [comment]
I have the exact same error when build as Angular Elements.

**Comment by KgotsoK** [comment]
Also just spotted the same issue. These are the Angular packages I'm using:

```
    "@angular/animations": "^6.0.7",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/router": "^6.0.7",
```

So the error goes:

```
ERROR Error: Unable to process animations due to the following failed trigger transitions
 @transformPanel has failed due to:

- `query("@fadeInCalendar")` returned zero elements. (Use `query("@fadeInCalendar", { optional: true })` if you wish to allow this.)


    at t.reportError (main.7e30741973d319bd7c18.js:1)
    at t._flushAnimations (main.7e30741973d319bd7c18.js:1)
    at t.flush (main.7e30741973d319bd7c18.js:1)
    at e.t.flush (main.7e30741973d319bd7c18.js:1)
    at main.7e30741973d319bd7c18.js:1
    at e.invoke (polyfills.7a0e6866a34e280f48e7.js:1)
    at t.run (polyfills.7a0e6866a34e280f48e7.js:1)
    at t.runOutsideAngular (main.7e30741973d319bd7c18.js:1)
    at t.end (main.7e30741973d319bd7c18.js:1)
    at t.detectChanges (main.7e30741973d319bd7c18.js:1)
```

And when the datepicker is open, there is an error that is triggered continuously but disappears after I close the datepicker:

```
ERROR TypeError: p.ngDoCheck is not a function
    at main.7e30741973d319bd7c18.js:1
    at main.7e30741973d319bd7c18.js:1
    at Ko (main.7e30741973d319bd7c18.js:1)
    at _a (main.7e30741973d319bd7c18.js:1)
    at Object.updateDirectives (main.7e30741973d319bd7c18.js:1)
    at Object.updateDirectives (main.7e30741973d319bd7c18.js:1)
    at Go (main.7e30741973d319bd7c18.js:1)
    at na (main.7e30741973d319bd7c18.js:1)
    at ta (main.7e30741973d319bd7c18.js:1)
    at Go (main.7e30741973d319bd7c18.js:1)
```

The above is probably the validator failing? In any case, the issue is there, @DevVersion.

**Comment by DevVersion** [comment]
Thanks for the updates. I will have another look tomorrow. 

Meanwhile, could someone share the template of the datepicker? (just to be sure)

**Comment by SeanAaa** [comment]
Rolled back to 6.3.0 and everything is working correctly again (it's the only thing I changed). Using CLI 6.0.8.

**Comment by scotthardin** [comment]
I'm using latest cli and ng.  Versions of node 8.11.2 and npm 6.1.0.  I've tried to reproduce using a new simpler project and failed.  

However, I found a fix that worked for me (I thought these days had passed):
`rm -rf node_modules; npm i`

Prior to doing this, I was getting these warnings when compiling with the build-optimizer:
WARNING in ./src/app/app.module.ngfactory.js
138:7344-7352 "export 'ɵd24' (imported as 'i68') was not found in '@angular/material/menu'

WARNING in ./src/app/app.component.ngfactory.js
143:1294-1302 "export 'ɵf24' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/examples/todos/todos.component.ngfactory.js
151:341-349 "export 'ɵf24' (imported as 'i21') was not found in '@angular/material/menu'

WARNING in ./src/app/app.component.ngfactory.js
154:166-174 "export 'ɵf24' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/examples/todos/todos.component.ngfactory.js
167:341-349 "export 'ɵf24' (imported as 'i21') was not found in '@angular/material/menu'

WARNING in ./src/app/app.component.ngfactory.js
170:166-174 "export 'ɵf24' (imported as 'i11') was not found in '@angular/material/menu'

WARNING in ./src/app/examples/todos/todos.component.ngfactory.js
183:341-349 "export 'ɵf24' (imported as 'i21') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
20:694-701 "export 'ɵd24' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
49:191-198 "export 'ɵf24' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./node_modules/@angular/material/menu/typings/index.ngfactory.js
68:152-159 "export 'ɵf24' (imported as 'i1') was not found in '@angular/material/menu'

WARNING in ./src/app/examples/examples.module.ngfactory.js
85:2014-2022 "export 'ɵd24' (imported as 'i22') was not found in '@angular/material/menu'
`

**Comment by DevVersion** [comment]
> My markup is the same as yours except for using formControlNames. Again, serving ng locally there's no issues, it's only when building w/ --build-optimizer.

That's clear. I constantly tried running `ng build --prod --build-optimizer`. I'm not sure how I can help with that issue if no one is able to reproduce it in a new app.

I will close the issue for now. This does not mean that I'm not listening to any updates here anymore. Just closing since there is apparently no reproduce-able issue (**yet**) .

**Comment by mdsaudali365** [comment]
A possible workaround:
Set buildOptimizer as false in angular.json. Output files are still the same size and the date picker works like a charm!

My config:
"@angular/cli": "~6.0.8"
"@angular/material": "^6.3.0"

**Comment by TzyHuan** [comment]
Have the same issue after updating both @angular/material and @angular/cdk from 6.3.0 to 6.4.6 .
When I used "ng build --prod"
not only datepicker, the mat-tree combined with mat-tree also got error. Besides, the property [panelWidth] of mat-input not work either.

the error from mat-tree as below:
```
ERROR Error: Uncaught (in promise): TypeError: a.ngOnDestroy is not a function
TypeError: a.ngOnDestroy is not a function
    at Ua (main.a04e041dad630a65e567.js:1) 
    at j (polyfills.99b05666391ec91781c2.js:1)
    at polyfills.99b05666391ec91781c2.js:1
    at e.invokeTask (polyfills.99b05666391ec91781c2.js:1)
    at Object.onInvokeTask (main.a04e041dad630a65e567.js:1)
    at e.invokeTask (polyfills.99b05666391ec91781c2.js:1)
    at t.runTask (polyfills.99b05666391ec91781c2.js:1)
    at d (polyfills.99b05666391ec91781c2.js:1)
    at t.invokeTask [as invoke] (polyfills.99b05666391ec91781c2.js:1)
    at _ (polyfills.99b05666391ec91781c2.js:1)
```

When using "ng build --prod --build-optimizer=false",
everything are working excellent!

@angular/cli : 6.0.8
@angular/cdk : 6.4.6
@angular/material : 6.4.6
