### ISSUE TITLE
slide-toggle - compilation issue after upgrade to 7-2 (HammerInput)

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#1035]
#### What is the current behavior?
```
ERROR in [default] [path_to_my_project]/webClient/node_modules/@angular2-material/slide-toggle/slide-toggle.d.ts:67:19 
Cannot find name 'HammerInput'.
```

#### Which versions of Angular, Material, OS, browsers are affected?
OSX
Node v5.1.0
NPM 3.60
angular 2.0.0-rc.5
material: 2.0.0-alpha.7-2

**Comment by m0t0r** [comment]
@maciejsobala see #977

**Comment by maciejsobala** [comment]
@m0t0r 

Thanks. Closing issue :)
