### ISSUE TITLE
5.0.0-rc0 error run with ionic

### ISSUE THREAD

**Issue by Gavin-cn** [angular/material2#8274]
2.0.0-beta.12 run with ionic is ok，when I update to 5.0.0-rc0, will expose error like:
```shell
Runtime Error
Cannot find module "rxjs/operators/debounceTime"
Stack
Error: Cannot find module "rxjs/operators/debounceTime"
    at Object.exports.errorObject.e (http://localhost:8100/build/vendor.js:44143:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:186994:76)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:131272:89)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.516 (http://localhost:8100/build/main.js:304:76)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.199 (http://localhost:8100/build/main.js:17:82)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

Ionic Framework: 3.8.0
Ionic App Scripts: 3.0.1
Angular Core: 4.4.4
Angular Compiler CLI: 4.4.4
Node: 6.11.4
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
```
here is my `package.json`:
```javascript
{
  "name": "Demo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.0.1",
    "@swimlane/ngx-datatable": "^10.0.5",
    "angular-tree-component": "^5.1.2",
    "angular2-esri-loader": "^1.0.0",
    "esri-loader": "^1.2.1",
    "hammerjs": "^2.0.8",
    "ionic-angular": "3.8.0",
    "ionicons": "3.0.0",
    "md2": "0.0.25",
    "moment": "^2.19.1",
    "ng2-dnd": "^4.2.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-tree": "^2.0.0-rc.1",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.0.1",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project"
}
```

**Comment by zijianhuang** [comment]
Duplicate of ##8263 which had provided a solution/workaround.

**Comment by crisbeto** [comment]
You need to update RxJS to at least 5.5.0.
