### ISSUE TITLE
No Mat-Menu in Material 6.3.0 PROD TypeError: t is not a function

### ISSUE THREAD

**Issue by kdubious** [angular/material2#11843]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Menu should appear, no error

#### What is the current behavior?

No Menu, but there is a console error

#### What are the steps to reproduce?

Publish a production build

#### What is the use-case or motivation for changing an existing behavior?

x

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/cli": "^6.0.8",
    "@angular/language-service": "^6.0.5",
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cdk": "^6.3.0",
    "@angular/material": "^6.3.0",

#### Is there anything else we should know?
This code worked fine in Material 6.0.1

The menu (mat-menu) does not appear, and in the console, I have this error:
`ERROR TypeError: t is not a function
    at main.869058825fa288d7bef6.js:1
    at Tr (main.869058825fa288d7bef6.js:1)
    at Or (main.869058825fa288d7bef6.js:1)
    at e.get (main.869058825fa288d7bef6.js:1)
    at yo (main.869058825fa288d7bef6.js:1)
    at vo (main.869058825fa288d7bef6.js:1)
    at ho (main.869058825fa288d7bef6.js:1)
    at Wo (main.869058825fa288d7bef6.js:1)
    at Object.Uo [as createEmbeddedView] (main.869058825fa288d7bef6.js:1)
    at t.createEmbeddedView (main.869058825fa288d7bef6.js:1)`

During build, I had this warning:

`WARNING in ./src/app/dashboard/dashboard.component.ngfactory.js
109:168-176 "export 'ɵf23' (imported as 'i13') was not found in '@angular/material/menu'`

**Comment by jelbourn** [comment]
Duplicate of #11844
