### ISSUE TITLE
[matMenuTriggerFor] throws TypeError: this._change.pipe is not a function in +5.0.0-rc0

### ISSUE THREAD

**Issue by guidedog51** [angular/material2#8741]
#### Bug, feature request, or proposal:
Bug.

Menu setup using button with [matMenuTriggerFor} was working in 2.0.0-beta.12.  Now view containing menu fails to render throwing TypeError: this._change.pipe is not a function

#### What is the expected behavior?
[matMenuTriggerFor] should display the configured menu

#### What is the current behavior?
View fails to render

#### What are the steps to reproduce?
Here's the logged error:
ng:///AppModule/AppComponent.ngfactory.js:92 ERROR TypeError: this._change.pipe is not a function
    at ViewportRuler.change (main-client.js:83817)
    at new ViewportRuler (main-client.js:83722)
    at VIEWPORT_RULER_PROVIDER_FACTORY (main-client.js:83848)
    at _callFactory (main-client.js:16111)
    at _createProviderInstance$1 (main-client.js:16059)
    at resolveNgModuleDep (main-client.js:16041)
    at _createClass (main-client.js:16086)
    at _createProviderInstance$1 (main-client.js:16056)
    at resolveNgModuleDep (main-client.js:16041)
    at _createClass (main-client.js:16090)
    at _createProviderInstance$1 (main-client.js:16056)
    at resolveNgModuleDep (main-client.js:16041)
    at NgModuleRef_.get (main-client.js:17266)
    at resolveDep (main-client.js:17762)
    at createClass (main-client.js:17632)
View_AppComponent_0 @ ng:///AppModule/AppComponent.ngfactory.js:92
ng:///AppModule/AppComponent.ngfactory.js:92 ERROR CONTEXT DebugContext_
View_AppComponent_0 @ ng:///AppModule/AppComponent.ngfactory.js:92
vendor.js:66821 Unhandled Promise rejection: this._change.pipe is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this._change.pipe is not a function
    at ViewportRuler.change (main-client.js:83817)
    at new ViewportRuler (main-client.js:83722)
    at VIEWPORT_RULER_PROVIDER_FACTORY (main-client.js:83848)
    at _callFactory (main-client.js:16111)
    at _createProviderInstance$1 (main-client.js:16059)
    at resolveNgModuleDep (main-client.js:16041)
    at _createClass (main-client.js:16086)
    at _createProviderInstance$1 (main-client.js:16056)
    at resolveNgModuleDep (main-client.js:16041)
    at _createClass (main-client.js:16090)
    at _createProviderInstance$1 (main-client.js:16056)
    at resolveNgModuleDep (main-client.js:16041)
    at NgModuleRef_.get (main-client.js:17266)
    at resolveDep (main-client.js:17762)
    at createClass (main-client.js:17632) TypeError: this._change.pipe is not a function
    at ViewportRuler.change (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:83817:48)
    at new ViewportRuler (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:83722:38)
    at VIEWPORT_RULER_PROVIDER_FACTORY (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:83848:27)
    at _callFactory (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16111:20)
    at _createProviderInstance$1 (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16059:26)
    at resolveNgModuleDep (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16041:17)
    at _createClass (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16086:68)
    at _createProviderInstance$1 (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16056:26)
    at resolveNgModuleDep (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16041:17)
    at _createClass (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16090:32)
    at _createProviderInstance$1 (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16056:26)
    at resolveNgModuleDep (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:16041:17)
    at NgModuleRef_.get (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:17266:16)
    at resolveDep (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:17762:45)
    at createClass (https://localhost:44337/dist/main-client.js?v=K68aH15ONa1TRH60QZj8j9uj9KFY_nOrzLgjxuwg5Cg:17632:32)
consoleError @ vendor.js:66821
vendor.js:66823 ZoneAwareError
consoleError @ vendor.js:66823

Here's the markup:
<div class='row app-content'>
    <mat-toolbar color="primary" class="top-toolbar">
        <div fxLayout="row" fxLayoutAlign="space-between center" fxFlex="100">
            <div class="toolbar-item">
                <img src="../../../../Images/NNNNNN logo.png" class="brand-logo" />
            </div>
            <div>
                <button mat-button [matMenuTriggerFor]="menu" class="profile_menu">
                    <span matPrefix class="logged-in-user">{{loggedInUser}}</span>
                    <mat-icon>account_circle</mat-icon>
                </button>
                <mat-menu #menu="matMenu">
                    <button mat-menu-item *ngIf="!isLoggedIn" (click)="logIn()">Login</button>
                    <button mat-menu-item *ngIf="isLoggedIn" (click)="logOut()">Logout</button>
                </mat-menu>
            </div>
        </div>
    </mat-toolbar>
    <div>
        <nav-menu></nav-menu>
    </div>
    <div class='body-content'>
        <router-outlet></router-outlet>
    </div>
</div>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome, FireFox, Edge all affected.   Dependencies are:

  "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "^5.0.3",
    "@angular/cdk": "^5.0.0-rc.2",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/flex-layout": "^2.0.0-beta.10-4905443",
    "@angular/forms": "^5.0.3",
    "@angular/http": "^5.0.3",
    "@angular/material": "^5.0.0-rc.2",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/platform-server": "^5.0.3",
    "@angular/router": "^5.0.3",
    "@types/node": "^7.0.18",
    "ajv": "^5.5.0",
    "angular2-adal": "0.1.4",
    "angular2-jwt": "0.2.3",
    "angular2-moment": "^1.7.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "3.0.1",
    "aspnet-webpack": "2.0.1",
    "awesome-typescript-loader": "^3.2.3",
    "bootstrap": "3.3.7",
    "core-js": "^2.5.1",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "hammerjs": "2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "moment": "^2.19.1",
    "ng2-adal": "2.0.0",
    "ng2-nvd3": "2.0.0",
    "nvd3": "git+https://github.com/InTechEnergy/nvd3.git",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.2",
    "sass-npm": "1.0.2",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "typescript": "^2.6.2",
    "url-loader": "0.5.8",
    "web-animations-js": "^2.3.1",
    "webpack": "^3.9.1",
    "webpack-hot-middleware": "^2.21.0",
    "webpack-merge": "^4.1.0",
    "zone.js": "^0.8.18"

tsconfig.ts:

{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "lib": [ "es6", "dom" ],
    "types": [ "node" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}

#### Is there anything else we should know?
This is a DotNetCore 2.0 MVC project.  Downgrading Angular/Material to 2.0.0-beta.12 fixes the issue
!
![mat-menu](https://user-images.githubusercontent.com/8183309/33449414-8d11c592-d5bd-11e7-94f2-76b39bfd7851.PNG)

**Comment by andrewseguin** [comment]
Please re-open with a reproduction of the issue

**Comment by brivvirs** [comment]
Similar issue
https://github.com/angular/material2/issues/8313#issuecomment-350545147
