### ISSUE TITLE
table: tsconfig target es6 causes `_elementRef` failure during table creation

### ISSUE THREAD

**Issue by epelc** [angular/material2#13695]
#### Bug, feature request, or proposal:
Seems like all of my uses of `<mat-table>` and `<table mat-table>` broke with an undefined `elementRef` after upgrading from 6.1.x to 7.0.0 using `ng update`.

#### What is the expected behavior?

Tables should render and not throw an error on start.

#### What is the current behavior?

I receive the following error.

```
core.js:15043 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined
TypeError: Cannot read property 'nativeElement' of undefined
    at new CdkTable (table.js:1071)
    at new MatTable (table.js:28)
    at createClass (core.js:23001)
    at createDirectiveInstance (core.js:22828)
    at createViewNodes (core.js:24376)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at createViewNodes (core.js:24405)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at new CdkTable (table.js:1071)
    at new MatTable (table.js:28)
    at createClass (core.js:23001)
    at createDirectiveInstance (core.js:22828)
    at createViewNodes (core.js:24376)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at createViewNodes (core.js:24405)
    at callViewAction (core.js:24825)
    at execComponentViewsAction (core.js:24731)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16954)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```

`_elementRef` is undefined for some reason.
![image](https://user-images.githubusercontent.com/5204642/47242132-e76fa980-d3bb-11e8-87df-f45f80bd8860.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Setup any type of mat-table and the cdk table constructor doesn't get it's element ref injected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0 w/ angular 7.0.0 on chrome 70.0.3538.67 (Official Build) (64-bit)

#### Is there anything else we should know?
Seems to be working on the docs. Wondering if it's just with upgraded apps? Going to check if a new gen app works with table.

**Comment by josephperrott** [comment]
Are you referencing the `_elementRef` for a table from your code?

Can you provide a reproduction of the issue you are seeing?

**Comment by epelc** [comment]
@josephperrott Just found the cause :)

I setup a new project trying to figure this out but a fresh cli project + `ng add @angular/material` on latest versions with a basic table component shows no errors. I tracked it down though to targeting `es6` instead of `es5` in the tsconfig.json.


ie `{    "target": "es6"}` causes this bug. Oddly enough I also noticed the polyfills for new projects are only enabled for evergreen browsers but they still target es5 by default for some reason?

**Comment by epelc** [comment]
@josephperrott Couldn't get a demo to load on stackblitz(not sure if it doesn't support angular v7 yet?) but here is a repo to reproduce this. 

https://github.com/epelc/bad-material-table

It has `target: "es6"` in the `tsconfig.json` with a basic table to show the bug. Just `npm install && npm start` and restart with target `es5` to show the table working.

**Comment by epelc** [comment]
Can this be reopened? I don't think the fix is working

I updated material and the cdk in the demo repo to version 7.0.1 which should include the fix but it doesn't seem to be working.
https://github.com/epelc/bad-material-table

![image](https://user-images.githubusercontent.com/5204642/47473972-f9e64a80-d7e2-11e8-8329-7e85b2c90db6.png)

**Comment by MendyBerger** [comment]
Possible duplicate of #9813

**Comment by GeorgeTailor** [comment]
Still doesn't work with
```
@angular/core@7.2.8
```
and 
```
@angular/material@7.3.3
```

Do you plan to support es6 or not ?

**Comment by epelc** [comment]
@GeorgeTailor iirc the current plan is to wait for angular core to fix their support for es6 as it is really the underlying issue for this and the related problems in `@angular/material`.

Use `target: "es5"` for now. Not sure but maybe angular 8 is the version they are going to fix this in since they are advertising differential version loading which would require es6 support to load the newer versions(they explicitly say es6 code will be loaded in newer browsers). So should be fixed pretty soon.

**Comment by MarkOsgood** [comment]
@GeorgeTailor 
I had the same _elementRef issue and was able to find a fix for it on these forums.
I verified it today using  Angular 7.2.9 with Material 2 7.3.5.
I target es6 and my tables work by using "**_ng serve- -aot_**" in the scripts section in package.json.
Without the **--aot** the tables still do not work and I get the same _elementRef error.
