### ISSUE TITLE
Typings issues after installing 6.4.4

### ISSUE THREAD

**Issue by AlQuraian** [angular/material2#12654]
After I updated to 6.4.4 I get these errors on serve:

```
ERROR in node_modules\@angular\material\datepicker\typings\index.d.ts.MatDatepickerContent.html(1,368): : Property '_select' does not exist on type 'MatDatepicker<any>'. Did you mean '_selected'?
node_modules\@angular\material\progress-bar\typings\index.d.ts.MatProgressBar.html(1,267): : Property '_rectangleFillValue' does not exist on type 'MatProgressBar'.
```

**Comment by tbeswick96** [comment]
Getting the same issue

**Comment by Eddygn** [comment]
Reinstalling the whole node_modules didn't help, had to revert back to 6.4.3

**Comment by paulimfavarato** [comment]
same issue here. just when I build --prod. the normal serve runs ok.

**Comment by jelbourn** [comment]
It looks like there was an error while publishing 6.4.4. The `latest` tag on npm has been set back to 6.4.3 and we'll be releasing a 6.4.5 shortly with the problem resolved.

**Comment by mmansouri** [comment]
Same issue here, rollback to 6.4.2 to fix the problem. Waiting  for a better solution
