### ISSUE TITLE
mdInput - this._hintChildren.find is not a function (2.0.0-beta.2)

### ISSUE THREAD

**Issue by BenStanley** [angular/material2#3199]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Standard mdInput text field

#### What is the current behavior?
This is the standard code used (taken from docs):
```
<md-input-container>
	<input mdInput placeholder="Favorite food" value="Sushi">
</md-input-container>
```
This is the error received:
```
EXCEPTION: Uncaught (in promise): Error: Error in ./PageProfileEdit class PageProfileEdit - inline template:11:4 caused by: this._hintChildren.find is not a function
TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (http://localhost:4200/main.bundle.js:37192:32)
```

#### What are the steps to reproduce?
On the latest version (2.0.0-beta.2) copying the mdInput code straight from the docs produces this error. It worked fine on 2.0.0-beta.1.

#### Which versions of Angular, Material, OS, browsers are affected?
angular/material2 2.0.0-beta.2
Chrome 56.0.2924.87 on Mac OS X 10.11.3

**Comment by teplyja1** [comment]
I had same issue.
Update of Angular2 libs to latest version (2.4.8) solved it.

**Comment by crisbeto** [comment]
The `QueryList.find` method was introduced with Angular 2.2 and Material supports 2.3 and above.
