### ISSUE TITLE
Erorr in production after 6.0.1 - > 6.2.1:Cannot read property 'ngInjectableDef' of undefined

### ISSUE THREAD

**Issue by theunreal** [angular/material2#11781]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
App should render and don't throw runtime error in production

#### What is the current behavior?
App throws error at runtime and app crashes

#### What are the steps to reproduce?
I just upgraded my app from 6.0.1 to 6.2.1, still not clue why this error appears - but revering back to 6.0.1 fixed it.

#### What is the use-case or motivation for changing an existing behavior?
Bugfix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.4
Material 6.2.1

#### Is there anything else we should know?
App worked in 6.0.1

**Comment by ScienceOfficer** [comment]
I also had problems when I switched from 6.02 to 6.21. In my case, it was this error:

ERROR Error: StaticInjectorError(AppModule)[MatSnackBarContainer -> MatSnackBarConfig]: 
StaticInjectorError(Platform: core)[MatSnackBarContainer -> MatSnackBarConfig]: 
NullInjectorError: No provider for MatSnackBarConfig!

This only happend in production mode, when the MatSnackBar should open. When using "ng serve" everything was fine.

I was almost getting crazy when I tried to find out what went wrong. Luckily reverting Angular Material to 6.02 helped. MatSnackBar is working again.

I really hope, it's okay to comment underneath this issue, as this problem seems quite similar to me.

**Comment by Coffee-Tea** [comment]
Any updates?

**Comment by kdubious** [comment]
@ScienceOfficer I would think your fix is to include MatSnackBarConfig in the providers node of your module.

For our issue, I'm stumped.

**Comment by kdubious** [comment]
Reverted `@angular/material` to 6.0.1, have these warnings still:

    WARNING in ./node_modules/@angular/material/tabs/typings/index.ngfactory.js
    120:77-95 "export 'ContentObserver' (imported as 'i3') was not found in '@angular/cdk/observers'
    WARNING in ./node_modules/@angular/material/tabs/typings/index.ngfactory.js
    153:77-95 "export 'ContentObserver' (imported as 'i3') was not found in '@angular/cdk/observers'

And same error while running.

**Comment by kdubious** [comment]
Reverted to `"@angular/cdk": "^6.0.1"` and no warnings. Also, no errors in production.

**Comment by tzachs** [comment]
I'm having the same issue after upgrade cdk to 6.2.1

main.js:1 ERROR TypeError: Cannot read property 'ngInjectableDef' of undefined
    at Tr (main.js:1)
    at t.get (main.js:1)
    at vo (main.js:1)
    at go (main.js:1)
    at po (main.js:1)
    at Wo (main.js:1)
    at na (main.js:1)
    at ta (main.js:1)
    at Wo (main.js:1)
    at na (main.js:1)

**Comment by tzachs** [comment]
@theunreal thank you for the revert advice :)

**Comment by tzachs** [comment]
I've now just updated both angular/cdk and angular/material to 6.3.0 and it seems to be fixed.

**Comment by kdubious** [comment]
6.3.0 creates a new issue for me:
https://github.com/angular/material2/issues/11843#issue-333664697

**Comment by kdubious** [comment]
This may solve it:
https://github.com/angular/material2/issues/11844#issuecomment-398496566

Mine seems OK now.

**Comment by tzachs** [comment]
I think deleting the node_modules and then running again npm install work, did it work for you @kdubious ?

**Comment by kdubious** [comment]
Yes, same package.json. Kill the @angular and rxjs folders and `npm install'. All good.

**Comment by josephperrott** [comment]
Closing as the original report is not reproducible, feel free to open a new issue with a bit more information on how to reproduce the problem.

For the other issues being discussed in this thread, it looks like it is likely related to #11844
