### ISSUE TITLE
No provider for Overlay!  StaticInjectorError(AppModule)[MatMenuTrigger -> Overlay]:

### ISSUE THREAD

**Issue by istiti** [angular/material2#10820]
#### Bug, feature request, or proposal:
bug

#### What are the steps to reproduce?
I update from angular 5.x and cli 1.7.x and rxjs 5.x to v6rc.x
I only update in my module this `MatMenuModule` and use it like:
```
<div *ngFor="let item of data">
  <button mat-icon-button [matMenuTriggerFor]="appMenu"></button>
  <mat-menu #appMenu="matMenu" [overlapTrigger]="false"
            class="slds-dropdown slds-dropdown_left slds-dropdown_actions">
    <ul class="slds-dropdown__list" role="menu">
      <li (click)="onClickCreerPO.emit({bail:item, nature:'Rent'})">
        <a href="javascript:void(0);">PO Loyer</a>
      </li>
      <li (click)="onClickCreerPO.emit({bail:item, nature:'AddedRent'})">
        <a href="javascript:void(0);">PO Surplus</a>
      </li>
    </ul>
  </mat-menu>
</div>
```

#### Before
It was working before update.

#### Current
![image](https://user-images.githubusercontent.com/2789203/38680656-247aacc0-3e67-11e8-927e-2e1ceac8ae24.png)

**Comment by cyrilletuzi** [comment]
Same error. It seems like one Material component now has a dependency to CDK OverlayModule, but it's not documented in the changelog.

**Comment by crisbeto** [comment]
@cyrilletuzi the menu module has always had a dependency on the `OverlayModule`, I don't think anything has changed recently.

@istiti are you able to reproduce the error in a Stackblitz?

**Comment by cyrilletuzi** [comment]
For me it's not the menu, I don't use this one. But I just upgraded from Material 5 to 6, without any change in my app, and no I have the same error, needing `OverlayModule`. So at least one of my Material module has this new dependency.

**Comment by cyrilletuzi** [comment]
For me it's `MatAutocompleteTrigger` which need `OverlayModule`.

**Comment by crisbeto** [comment]
The autocomplete module has also had the `OverlayModule` import for a long time now. We haven't even [touched that line in more than six months](https://github.com/angular/material2/blame/master/src/lib/autocomplete/autocomplete-module.ts#L19).

**Comment by cyrilletuzi** [comment]
Then there really is an issue: I have to manually add the `OverlayModule` in my `AppModule` for the `mat-autocomplete` to continue to work in v6, and that doesn't seem normal if it's already imported.

**Comment by cyrilletuzi** [comment]
After some tests, it appears it only happen in v6 when the module where `MatAutocomplete` is used is lazy-loaded.

**Comment by istiti** [comment]
Breaking change to my code or i used it wrongly but was working well in v5 simply adding MatMenuModule in certain lazymodule yes 😞

**Comment by cyrilletuzi** [comment]
@crisbeto Yep, everything (Angular / Material / CLI) is in v6 very last RC.

**Comment by StriesseParadise** [comment]
I've the same issue with the MatMenuTrigger.
Is there any workaround, which can make it work until the problem is solved?

**Comment by yokots** [comment]
when i import the overlay module in a lazy loading module it also dosen't work.

**Comment by yushihui** [comment]
Today I updated to angular 6 have the same issue,


ERROR Error: StaticInjectorError(WzzModule)[MatMenuTrigger -> Overlay]: 
  StaticInjectorError(Platform: core)[MatMenuTrigger -> Overlay]: 
    NullInjectorError: No provider for Overlay!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveNgModuleDep (core.js:9238)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9919)
    at inject (core.js:1334)

**Comment by yushihui** [comment]
@yokots 
I tried your fix, but it does not work for me

**Comment by yushihui** [comment]
when I add
import {OverlayModule} from '@angular/cdk/overlay';
to my root module
it works

**Comment by keatkeat87** [comment]
![image](https://user-images.githubusercontent.com/8691013/39659455-eebacb6e-505a-11e8-94de-83620b055215.png)
i think this cause Overlay must provide in root injector.

**Comment by Eddygn** [comment]
Having similar issue due to [matTooltip]. 
Project was upgraded to 6 (release)

```
ERROR Error: StaticInjectorError(AppModule)[CdkConnectedOverlay -> Overlay]: 
  StaticInjectorError(Platform: core)[CdkConnectedOverlay -> Overlay]: 
    NullInjectorError: No provider for Overlay!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get
```
Hope it helps

**Comment by yokots** [comment]
@crisbeto [here](https://stackblitz.com/edit/angular-q68gih) is an example in Stackblitz

**Comment by Tyler-V** [comment]
What about if importing OverlayModule at the app.module.ts isn't an option? I am shipping a component at a library that uses material.

Importing OverlayModule at the library.module does not resolve the issue, only if I import it at the app.module of the project that uses my library... this would require the user to perform additional setup instead of just being able to import my library.

Is there anyway around this?

```
StaticInjectorError(Platform: core)[MatMenuTrigger -> Overlay]: 
    NullInjectorError: No provider for Overlay!
```

**Comment by AnthonyNahas** [comment]
I am facing the same problem with matToolTip -->

```
core.js:1601 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[MatTooltip -> Overlay]: 
  StaticInjectorError(Platform: core)[MatTooltip -> Overlay]: 
    NullInjectorError: No provider for Overlay!
Error: StaticInjectorError(AppModule)[MatTooltip -> Overlay]: 
  StaticInjectorError(Platform: core)[MatTooltip -> Overlay]: 
    NullInjectorError: No provider for Overlay!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at 
```

Im getting the error since I updated angular from v5 to v6

**Comment by CharlBest** [comment]
Yes this is also breaking for me after updating to v6.

ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[MatTooltip -> Overlay]: 
  StaticInjectorError(Platform: core)[MatTooltip -> Overlay]: 
    NullInjectorError: No provider for Overlay!
Error: StaticInjectorError(AppModule)[MatTooltip -> Overlay]: 
  StaticInjectorError(Platform: core)[MatTooltip -> Overlay]: 
    NullInjectorError: No provider for Overlay!

**Comment by renatop7** [comment]
For everyone having problems with the `NullInjectorError: No provider for Overlay!` when trying to lazy load, just try to add OverlayModule to app.module imports, or your root module, for me it worked like a charm.

It's a temporary fix until they update the code...

**Comment by Tyler-V** [comment]
@renatop7 I too saw that referenced in another issue however that doesn't work for me inside a library, importing it inside the project's module or app module results in the same error.

**Comment by renatop7** [comment]
@Tyler-V Yeah, it seems another problem.
What you could do is try to implement a forRoot() method in your library, and add the Overlay provider in there.
I'm not sure if this would help you, and I can't test it, but it was something that came to mind when I read your response.

**Comment by AnthonyNahas** [comment]
@renatop7 you have right! The only way to get that thing working is to import `OverlayModule`
in the app component (the root) module and not in the lazy loaded module..... 🍰

**Comment by matheusdavidson** [comment]
Same problem with v6 and Material Datepicker.
Importing ```OverlayModule``` into ```app.module```(must be loaded here) solved the problem.

**Comment by cgatian** [comment]
@jelbourn It would be nice when regressions are found if there was a milestone/timeline created to provide insight on when merged issues would be released.

**Comment by wangyud** [comment]
@yushihui @matheusdavidson I do this . but it doesn't work

**Comment by fazpu** [comment]
Hi, I had the same problem.

Turned out it was caused by importing `@import '~bootstrap/scss/bootstrap';` in `styles.scss`

I ended up importing only 
```
@import '~bootstrap/scss/bootstrap-grid';
@import '~bootstrap/scss/mixins';
@import '~bootstrap/scss/utilities';
```

This was sufficient for my needs and the error went away.

**Comment by idzer0lis** [comment]
The quickfix does not work for a NgModule created with the TestBed..
Error: StaticInjectorError(DynamicTestModule)[MatDialog -> Overlay]: 
````
TestBed.configureTestingModule({
      providers: [
        UiEffects,
        // MatDialogModule,
        OverlayModule,
        // MatDialog,
        DialogService,
       .....
````

**Comment by andrewtw** [comment]
Just wanna check if the issue fixed in the latest version `6.4.6`, because our app still encounter the same problem after the upgrading to `6.4.6`.

**Comment by andrewtw** [comment]
Just confirmed `6.4.6` doesn't fix this issue.

Reproduce:
https://stackblitz.com/edit/angular-hwydpn?file=src%2Fapp%2Fapp.module.ts

@crisbeto @tinayuangao 
But why the issue is closed?

**Comment by michaelspeed** [comment]
i am still getting this error, although i have added OverlayModule in the AppModule.
i even tried adding them to all the LazyLoad Modules, still no fix

**Comment by Maryannah** [comment]
Hello, 

Although I am late to the post, I am facing the same issue. 

I have created a showcase project for a library I'm coding. When using a custom overlay service that I wrote, I faced the error. 

Simply providing my service into the module, instead of using `providedIn: root` solved the issue. 

I'm posting that just in case someone encounters the same issue in the same case. 

Sorry I bothered you all !

**Comment by SarveshDeshmukh** [comment]
> Hello,
> 
> Although I am late to the post, I am facing the same issue.
> 
> I have created a showcase project for a library I'm coding. When using a custom overlay service that I wrote, I faced the error.
> 
> Simply providing my service into the module, instead of using `providedIn: root` solved the issue.
> 
> I'm posting that just in case someone encounters the same issue in the same case.
> 
> Sorry I bothered you all !

This worked for me!

**Comment by deepthan** [comment]
If you use ng-zorro-antd, you can try it with the following versions:
```
 "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "core-js": "^2.6.3",
    "ng-zorro-antd": "^7.0.3",
    "zone.js": "~0.8.29"
 },
 "devDependencies": {
    "@angular-devkit/build-angular": "0.12.3",
    "@angular/cli": "~7.3.6",
    "@angular/compiler-cli": "^7.2.9",
    "@angular/language-service": "^7.2.9",
    "@angularclass/hmr": "^2.1.3",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~11.11.4",
    "codelyzer": "~5.0.0-beta.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.0.3",
    "tslint": "~5.14.0",
    "typescript": "3.2.4"
  }
```

**Comment by vanessaLatefa** [comment]
Hello, Im also facing this error, and I dont know how to fix it..
I am lazy loading my log in from a home module..
Login has Auth service and Auth guard.
Please help!

[Error] ERROR – Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[LoginComponent -> MatSnackBar]: 
  StaticInjectorError(Platform: core)[LoginComponent -> MatSnackBar]: 
    NullInjectorError: No provider for MatSnackBar!
get@http://localhost:4200/vendor.js:69847:28
resolveToken@http://localhost:4200/vendor.js:70092:27
tryResolveToken@http://localhost:4200/vendor.js:70036:28
get@http://localhost:4200/vendor.js:69933:35
resolveToken@http://localhost:4200/vendor.js:70092:27
tryResolveToken@http://localhost:4200/vendor.js:70036:28
get@http://localhost:4200/vendor.js:69933:35
resolveNgModuleDep@http://localhost:4200/vendor.js:82169:32
resolveNgModuleDep@http://localhost:4200/vendor.js:82169:32
createClass@http://localhost:4200/vendor.js:83109:42
createDirectiveInstance@http://localhost:4200/vendor.js:82980:31
createViewNodes@http://localhost:4200/vendor.js:84206:59
createRootView@http://localhost:4200/vendor.js:84120:20
callWithDebugContext@http://localhost:4200/vendor.js:85128:30
create@http://localhost:4200/vendor.js:82459:43
createComponent@http://localhost:4200/vendor.js:82570:51
activateWith@http://localhost:4200/vendor.js:140637:55
activateRoutes@http://localhost:4200/vendor.js:137870:52
http://localhost:4200/vendor.js:137821:33
forEach@[native code]
activateChildRoutes@http://localhost:4200/vendor.js:137820:36
activateRoutes@http://localhost:4200/vendor.js:137877:41
http://localhost:4200/vendor.js:137821:33
forEach@[native code]
activateChildRoutes@http://localhost:4200/vendor.js:137820:36
activate@http://localhost:4200/vendor.js:137745:33
http://localhost:4200/vendor.js:137729:22
_next@http://localhost:4200/vendor.js:149768:39
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:152131:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
http://localhost:4200/vendor.js:146661:24
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:152110:115
_next@http://localhost:4200/vendor.js:152100:23
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:152131:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
_complete@http://localhost:4200/vendor.js:152298:33
complete@http://localhost:4200/vendor.js:144494:27
_complete@http://localhost:4200/vendor.js:144512:34
complete@http://localhost:4200/vendor.js:144494:27
_complete@http://localhost:4200/vendor.js:150053:38
complete@http://localhost:4200/vendor.js:144494:27
http://localhost:4200/vendor.js:155159:32
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:150048:90
_tryNext@http://localhost:4200/vendor.js:150042:23
_next@http://localhost:4200/vendor.js:150025:26
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
http://localhost:4200/vendor.js:146661:24
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:152110:115
_next@http://localhost:4200/vendor.js:152100:23
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149213:34
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[LoginComponent -> MatSnackBar]: 
  StaticInjectorError(Platform: core)[LoginComponent -> MatSnackBar]: 
    NullInjectorError: No provider for MatSnackBar!
get@http://localhost:4200/vendor.js:69847:28
resolveToken@http://localhost:4200/vendor.js:70092:27
tryResolveToken@http://localhost:4200/vendor.js:70036:28
get@http://localhost:4200/vendor.js:69933:35
resolveToken@http://localhost:4200/vendor.js:70092:27
tryResolveToken@http://localhost:4200/vendor.js:70036:28
get@http://localhost:4200/vendor.js:69933:35
resolveNgModuleDep@http://localhost:4200/vendor.js:82169:32
resolveNgModuleDep@http://localhost:4200/vendor.js:82169:32
createClass@http://localhost:4200/vendor.js:83109:42
createDirectiveInstance@http://localhost:4200/vendor.js:82980:31
createViewNodes@http://localhost:4200/vendor.js:84206:59
createRootView@http://localhost:4200/vendor.js:84120:20
callWithDebugContext@http://localhost:4200/vendor.js:85128:30
create@http://localhost:4200/vendor.js:82459:43
createComponent@http://localhost:4200/vendor.js:82570:51
activateWith@http://localhost:4200/vendor.js:140637:55
activateRoutes@http://localhost:4200/vendor.js:137870:52
http://localhost:4200/vendor.js:137821:33
forEach@[native code]
activateChildRoutes@http://localhost:4200/vendor.js:137820:36
activateRoutes@http://localhost:4200/vendor.js:137877:41
http://localhost:4200/vendor.js:137821:33
forEach@[native code]
activateChildRoutes@http://localhost:4200/vendor.js:137820:36
activate@http://localhost:4200/vendor.js:137745:33
http://localhost:4200/vendor.js:137729:22
_next@http://localhost:4200/vendor.js:149768:39
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:152131:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
http://localhost:4200/vendor.js:146661:24
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:152110:115
_next@http://localhost:4200/vendor.js:152100:23
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:152131:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
_complete@http://localhost:4200/vendor.js:152298:33
complete@http://localhost:4200/vendor.js:144494:27
_complete@http://localhost:4200/vendor.js:144512:34
complete@http://localhost:4200/vendor.js:144494:27
_complete@http://localhost:4200/vendor.js:150053:38
complete@http://localhost:4200/vendor.js:144494:27
http://localhost:4200/vendor.js:155159:32
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:150048:90
_tryNext@http://localhost:4200/vendor.js:150042:23
_next@http://localhost:4200/vendor.js:150025:26
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
http://localhost:4200/vendor.js:146661:24
_trySubscribe@http://localhost:4200/vendor.js:143863:35
subscribe@http://localhost:4200/vendor.js:143849:35
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
subscribe@http://localhost:4200/vendor.js:143844:26
_innerSub@http://localhost:4200/vendor.js:152110:115
_next@http://localhost:4200/vendor.js:152100:23
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149213:34
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:152492:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23
_next@http://localhost:4200/vendor.js:149774:30
next@http://localhost:4200/vendor.js:144482:23
notifyNext@http://localhost:4200/vendor.js:150058:30
_next@http://localhost:4200/vendor.js:143701:31
next@http://localhost:4200/vendor.js:144482:23resolvePromise — zone.js:831resolvePromise — zone.js:788(anonymous function) — zone.js:892onInvokeTask — core.js:17289runTask — zone.js:195drainMicroTaskQueue — zone.js:601promiseReactionJob
	defaultErrorLogger (vendor.js:76675)
	handleError (vendor.js:76723)
	next (vendor.js:78722:140)
	(anonymous function) (vendor.js:74466)
	__tryOrUnsub (vendor.js:144624)
	next (vendor.js:144562)
	_next (vendor.js:144505)
	next (vendor.js:144482)
	next (vendor.js:144247)
	emit (vendor.js:74450)
	run (polyfills.js:2508)
	onHandleError (vendor.js:78272)
	runGuarded (polyfills.js:2522)
	_loop_1 (polyfills.js:3052)
	microtaskDrainDone (polyfills.js:3061)
	drainMicroTaskQueue (polyfills.js:2966)
	promiseReactionJob

**Comment by lppedd** [comment]
Same problem after updating to Angular 8.

**Comment by billbarni** [comment]
Same problem. Angular 7.2.

**Comment by Vasu6916** [comment]
import { Overlay } from '@angular/cdk/overlay' in the spec file 
This fixed the issue for me
